#!/usr/bin/env python3
"""
Hook scaffold templates (Cycle 3).
===================================
Generates boilerplate Python and Bash skeletons for each Claude Code hook
event. The scaffolds encode the patterns the cycle-1 research brief flagged:
  - stdin parse with fail-open (exit 0 on garbage input)
  - diagnostic log per Sacred Rule #5
  - timeout discipline (no blocking calls beyond per-event budget)
  - Windows-Python compat shim (matches subagent_capture.sh:8-9)
  - PostToolUse drift handling (read both `tool_response` AND `tool_result`)
  - SubagentStop extension fields (`agent_transcript_path`,
    `last_assistant_message`)

These are NOT recommendations the harness imposes — they're starting points
for new hook authors. Editable per project. The harness verifies that
HOOKS that follow these templates pass the side-effect manifest.

CLI:
    python scaffolds.py list                 # list available templates
    python scaffolds.py emit <event> <lang>  # print scaffold to stdout
    python scaffolds.py write <event> <lang> --out <path>  # write to disk

Sacred Rule alignment:
  Rule 2: scaffolds are read templates — they don't auto-install hooks.
  Rule 4 (only-asked): writing happens only on explicit `write` cmd.
  Rule 9 (no options): scaffolds are AAA defaults — opinionated.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, OSError):
    pass


# -----------------------------------------------------------------------------
# Templates
# -----------------------------------------------------------------------------


PYTHON_PROLOGUE = '''#!/usr/bin/env python3
"""
{event} hook — {description}.
Generated by hook_engineer/scaffolds.py.

Contract:
  - stdin: JSON payload from Claude Code
  - stdout/stderr: whatever you want; never block teardown
  - exit code 0 always (fail-open per hook contract)
  - latency budget: {budget_ms}ms (per Cycle 2 spec)

Diagnostic log: ~/.claude/telemetry/brain/{log_name}.log
"""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# Ensure UTF-8 stdout/stderr on Windows
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, OSError):
    pass

LOG = Path.home() / ".claude" / "telemetry" / "brain" / "{log_name}.log"


def parse_payload() -> dict:
    """Read JSON from stdin. Fail-open with empty dict on garbage."""
    try:
        raw = sys.stdin.read()
        if not raw.strip():
            return {{}}
        return json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        return {{}}


def diag(line: str) -> None:
    """Append a single diagnostic line. Never raises."""
    try:
        LOG.parent.mkdir(parents=True, exist_ok=True)
        with LOG.open("a", encoding="utf-8") as f:
            f.write(f"{{datetime.now(timezone.utc).isoformat()}} {{line}}\\n")
    except OSError:
        pass


def main() -> int:
    payload = parse_payload()
    session_id = payload.get("session_id", "")
'''

PYTHON_EPILOGUE = '''
    diag(f"ok session={{session_id}}")
    return 0


if __name__ == "__main__":
    # Always exit 0 — never block session per hook contract
    try:
        main()
    except Exception as e:  # noqa: BLE001
        diag(f"ERROR {{type(e).__name__}}: {{e}}")
    sys.exit(0)
'''


BASH_PROLOGUE = '''#!/usr/bin/env bash
# ============================================================================
# {event} hook — {description}.
# Generated by hook_engineer/scaffolds.py.
#
# Contract:
#   - stdin: JSON payload from Claude Code
#   - exit code 0 always (fail-open)
#   - latency budget: {budget_ms}ms (per Cycle 2 spec)
#
# Diagnostic log: ~/.claude/telemetry/brain/{log_name}.log
# ============================================================================

set +e

LOG="$HOME/.claude/telemetry/brain/{log_name}.log"
mkdir -p "$(dirname "$LOG")" 2>/dev/null

# Read stdin
STDIN_DATA=$(cat)

# Pure-shell JSON extraction (avoids MSYS-bash + WindowsApps Python stub bug
# verified 2026-05-02 — see token_accountant_receipt.sh for backstory).
SESSION_ID=$(printf '%s' "$STDIN_DATA" | grep -o '"session_id"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"\\([^"]*\\)"$/\\1/')

# Diagnostic log entry per Sacred Rule #5
{{
    echo "----"
    echo "run: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "session_id: $SESSION_ID"
'''

BASH_EPILOGUE = '''
}} >> "$LOG" 2>&1

# Always exit 0 — never block session teardown
exit 0
'''


# -----------------------------------------------------------------------------
# Per-event body fragments (the meat between prologue and epilogue)
# -----------------------------------------------------------------------------


PYTHON_BODIES = {
    "SessionStart": """
    cwd = payload.get("cwd", "")
    transcript_path = payload.get("transcript_path", "")
    # Your SessionStart logic here (e.g. warm a cache, log boot, snapshot env)
""",
    "UserPromptSubmit": """
    prompt = payload.get("prompt", "")
    model = payload.get("model", "")
    # Your UserPromptSubmit logic here
    # (e.g. classify prompt, log decision, mutate cache)
""",
    "PostToolUse": """
    tool_name = payload.get("tool_name", "")
    tool_input = payload.get("tool_input", {})
    # Drift handling: docs say `tool_result`, Toke shipped emits `tool_response`
    tool_output = payload.get("tool_response", payload.get("tool_result"))
    # Your PostToolUse logic here
""",
    "SessionEnd": """
    cwd = payload.get("cwd", "")
    reason = payload.get("reason", "")
    # Your SessionEnd logic here (cost report, learning write, breadcrumb)
""",
    "PreCompact": """
    transcript_path = payload.get("transcript_path", "")
    trigger = payload.get("trigger", "")
    # Your PreCompact logic here (snapshot pre-compact state)
""",
    "SubagentStop": """
    agent_id = payload.get("agent_id", "")
    agent_type = payload.get("agent_type", "")
    # Toke extension fields per subagent_capture.sh:31-32
    transcript_path = payload.get("agent_transcript_path", "")
    last_msg = (payload.get("last_assistant_message", "") or "")[:200]
    # Your SubagentStop logic here
""",
}


BASH_BODIES = {
    "SessionStart": """
    echo "event: SessionStart"
""",
    "UserPromptSubmit": """
    PROMPT_HEAD=$(printf '%s' "$STDIN_DATA" | grep -o '"prompt"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1)
    echo "event: UserPromptSubmit  prompt_preview=${PROMPT_HEAD:0:80}"
""",
    "PostToolUse": """
    TOOL=$(printf '%s' "$STDIN_DATA" | grep -o '"tool_name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"\\([^"]*\\)"$/\\1/')
    echo "event: PostToolUse  tool=$TOOL"
""",
    "SessionEnd": """
    echo "event: SessionEnd"
""",
    "PreCompact": """
    echo "event: PreCompact"
""",
    "SubagentStop": """
    AGENT=$(printf '%s' "$STDIN_DATA" | grep -o '"agent_type"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"\\([^"]*\\)"$/\\1/')
    echo "event: SubagentStop  agent_type=$AGENT"
""",
}


EVENT_DESCRIPTIONS = {
    "SessionStart": "fires once at session open",
    "UserPromptSubmit": "fires on every user prompt",
    "PostToolUse": "fires after each tool call",
    "SessionEnd": "fires once at session close",
    "PreCompact": "fires before transcript compaction",
    "SubagentStop": "fires when a spawned Agent subagent finishes",
}


EVENT_BUDGETS_MS = {
    "SessionStart": 500,
    "UserPromptSubmit": 500,
    "PostToolUse": 300,
    "SessionEnd": 2000,
    "PreCompact": 500,
    "SubagentStop": 500,
}


def emit(event: str, lang: str, *, log_name: str | None = None) -> str:
    if event not in PYTHON_BODIES:
        raise ValueError(f"Unknown event '{event}'. "
                         f"Choices: {sorted(PYTHON_BODIES.keys())}")
    if lang not in ("py", "bash"):
        raise ValueError("lang must be 'py' or 'bash'")
    log_name = log_name or f"{event.lower()}_hook"
    desc = EVENT_DESCRIPTIONS[event]
    budget = EVENT_BUDGETS_MS[event]
    if lang == "py":
        return (
            PYTHON_PROLOGUE.format(event=event, description=desc,
                                   budget_ms=budget, log_name=log_name)
            + PYTHON_BODIES[event]
            + PYTHON_EPILOGUE
        )
    return (
        BASH_PROLOGUE.format(event=event, description=desc,
                             budget_ms=budget, log_name=log_name)
        + BASH_BODIES[event]
        + BASH_EPILOGUE
    )


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="scaffolds")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="list available scaffold templates")

    p_emit = sub.add_parser("emit", help="print scaffold to stdout")
    p_emit.add_argument("event", choices=sorted(PYTHON_BODIES.keys()))
    p_emit.add_argument("lang", choices=["py", "bash"])
    p_emit.add_argument("--log-name", default=None,
                        help="diagnostic log basename (default: <event>_hook)")

    p_write = sub.add_parser("write", help="write scaffold to file (will not overwrite)")
    p_write.add_argument("event", choices=sorted(PYTHON_BODIES.keys()))
    p_write.add_argument("lang", choices=["py", "bash"])
    p_write.add_argument("--out", required=True)
    p_write.add_argument("--log-name", default=None)
    p_write.add_argument("--force", action="store_true",
                         help="overwrite if --out exists")

    args = p.parse_args(argv)

    if args.cmd == "list":
        for ev in sorted(PYTHON_BODIES.keys()):
            budget = EVENT_BUDGETS_MS[ev]
            desc = EVENT_DESCRIPTIONS[ev]
            print(f"{ev:18s} budget={budget}ms  {desc}")
        return 0

    if args.cmd == "emit":
        print(emit(args.event, args.lang, log_name=args.log_name))
        return 0

    if args.cmd == "write":
        path = Path(args.out)
        if path.exists() and not args.force:
            print(f"REFUSE: {path} exists (use --force to overwrite)", file=sys.stderr)
            return 1
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(emit(args.event, args.lang, log_name=args.log_name),
                        encoding="utf-8")
        # Make bash scripts executable
        if args.lang == "bash":
            try:
                path.chmod(0o755)
            except OSError:
                pass
        print(f"wrote {path}")
        return 0

    return 0


if __name__ == "__main__":
    sys.exit(main())
